[package]
name = "moku-daemon"
version = "0.1.1"
edition = "2024"

[lib]
name = "moku_daemon"
path = "src/lib.rs"

[dependencies]
moku-core.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
arc-swap.workspace = true
futures.workspace = true
auto-launch.workspace = true
sysinfo.workspace = true
ratatui.workspace = true
crossterm.workspace = true
async-trait.workspace = true
serde_json.workspace = true
serde.workspace = true

moku-rss = { path = "../modules/moku-rss", default-features = false }
