[package]
name = "moku-todo"
version = "0.1.1"
edition = "2024"

[dependencies]
moku-core.workspace = true
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
rand.workspace = true

[dev-dependencies]
tempfile.workspace = true
arc-swap.workspace = true
tokio.workspace = true
