[package]
name = "moku-bin"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "moku"
path = "src/main.rs"

[features]
default = ["lua-plugins"]
lua-plugins = ["dep:moku-lua"]

[dependencies]
moku-core.workspace = true
moku-lua = { path = "../moku-lua", optional = true }
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
clap.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
directories.workspace = true
async-trait.workspace = true
arc-swap.workspace = true
futures.workspace = true
sysinfo.workspace = true
auto-launch.workspace = true
rpassword.workspace = true
toml.workspace = true

moku-launcher = { path = "../modules/moku-launcher" }
moku-lock-screen = { path = "../modules/moku-lock-screen" }
moku-todo = { path = "../modules/moku-todo" }
moku-settings = { path = "../modules/moku-settings" }
moku-dashboard = { path = "../modules/moku-dashboard" }
moku-bookmark = { path = "../modules/moku-bookmark" }
moku-context = { path = "../modules/moku-context" }
moku-commit = { path = "../modules/moku-commit" }
moku-rss = { path = "../modules/moku-rss" }
moku-daemon = { path = "../moku-daemon" }
moku-vault-daemon = { path = "../moku-vault-daemon" }
moku-satz = { path = "../modules/moku-satz" }
moku-secrets = { path = "../modules/moku-secrets" }
moku-http = { path = "../modules/moku-http" }

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.build-dependencies]
winfsp = { version = "0.13", features = ["delayload"] }

[build-dependencies]
