[package]
name = "moku-bookmark"
version = "0.1.0"
edition = "2024"

[dependencies]
moku-core.workspace = true
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
arboard.workspace = true
regex.workspace = true
